---

- name: Run Cat 2 STIG 21xxxx tasks
  ansible.builtin.import_tasks:
    file: RHEL-09-21xxxx.yml

- name: Run Cat 2 STIG 23xxxx tasks
  ansible.builtin.import_tasks:
    file: RHEL-09-23xxxx.yml
