---

- name: Systemd_daemon_reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Change_requires_reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true

- name: Sshd_restart
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Remount_home
  ansible.posix.mount:
    name: /home
    state: remounted

- name: Remount_tmp
  ansible.posix.mount:
    name: /tmp
    state: remounted

- name: Remount_var
  ansible.posix.mount:
    name: /var
    state: remounted

- name: Remount_var_log
  ansible.posix.mount:
    name: /var/log
    state: remounted

- name: Remount_var_log_audit
  ansible.posix.mount:
    name: /var/log/audit
    state: remounted

- name: Remount_var_tmp
  ansible.posix.mount:
    name: /var/tmp
    state: remounted

- name: Reload_sysctl
  ansible.builtin.shell: sysctl --system

- name: Reload_tmux
  ansible.builtin.shell: tmux source-file /etc/tmux.conf

- name: Rebuild_grub
  ansible.builtin.shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Firewalld_reload
  ansible.builtin.shell: firewall-cmd --reload

- name: Restart_NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart_ssh
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart_sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
  when: "'sssd' in ansible_facts.packages"

- name: Update_aliases
  ansible.builtin.shell: newaliases

- name: Update_dconf
  ansible.builtin.shell: dconf update

- name: Build_aide_db
  notify: Check_aide
  ansible.builtin.shell: /usr/sbin/aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz

- name: Check_aide
  ansible.builtin.shell: /usr/sbin/aide --check

- name: Restart_aide
  ansible.builtin.systemd:
    name: aide
    state: restarted

- name: Restart_rsyslog
  ansible.builtin.systemd:
    name: rsyslog.service
    state: restarted
