---

- name: Systemd_daemon_reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Change_requires_reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true

- name: Sshd_restart
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Remount_home
  ansible.posix.mount:
    name: /home
    state: remounted

- name: Remount_tmp
  ansible.posix.mount:
    name: /tmp
    state: remounted

- name: Remount_var
  ansible.posix.mount:
    name: /var
    state: remounted

- name: Remount_var_log
  ansible.posix.mount:
    name: /var/log
    state: remounted

- name: Remount_var_log_audit
  ansible.posix.mount:
    name: /var/log/audit
    state: remounted

- name: Remount_var_tmp
  ansible.posix.mount:
    name: /var/tmp
    state: remounted

- name: Reload_sysctl
  ansible.builtin.shell: sysctl --system

- name: Rebuild_grub
  ansible.builtin.shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Firewalld_reload
  ansible.builtin.shell: firewall-cmd reload
