---
- name: HIGH | RHEL-09-252070 | There must be no shosts.equiv files on RHEL 9.
  when:
    - rhel9stig_disruption_high
    - rhel_09_252070
  vars:
    warn_control_id: RHEL-09-252070
  tags:
    - RHEL-09-252070
    - CAT1
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-257955r925852_rule
    - V-257955
    - NIST800-53R4_CM-6
  block:
    - name: HIGH | RHEL-09-252070 | AUDIT | There must be no shosts.equiv files on RHEL 9. | find files
      ansible.builtin.find:
        path: /
        pattern: shosts.equiv
      register: shosts_equiv

    - name: HIGH | RHEL-09-252070 | PATCH | There must be no shosts.equiv files on RHEL 9. | Remove files
      when:
        - rhel9stig_disruption_high
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ shosts_equiv.files }}"

    - name: HIGH | RHEL-09-252070 | PATCH | There must be no shosts.equiv files on RHEL 9. | Warn if not removing files found
      when:
        - shosts_equiv.files | length > 0
        - not rhel9stig_disruption_high
      ansible.builtin.import_tasks: warning_facts.yml
