---
- name: HIGH | RHEL-09-212020 | PATCH | RHEL 9 must require a unique superusers name upon booting into single-user and maintenance modes.
  when:
    - rhel_09_212020
  ansible.builtin.lineinfile:
    insertafter: "{{ grub_superusers.after }}"
    line: "{{ grub_superusers.line }}"
    path: /etc/grub2.cfg
    regexp: "{{ grub_superusers.regexp }}"
  loop:
    - regexp: ^set_superusers=
      line: set superusers="{{ rhel9stig_grub_superuser }}
      after: "### BEGIN /etc/grub.d/01_users ###"
    - { regexp: export superusers, line: export superusers, after: set_superusers= }
  loop_control:
    label: "{{ grub_superusers.line }}"
    loop_var: grub_superusers
  tags:
    - RHEL-09-212020
    - CAT1
    - CCI-000213
    - SRG-OS-000080-GPOS-00048
    - SV-257789r925354_rule
    - V-257789
    - NIST800-53R4_AC-3
