---
- name: HIGH | RHEL-09-672030 | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package.
  when:
    - rhel_09_672030
    - not ansible_facts.fips
  tags:
    - RHEL-09-672030
    - CAT1
    - CCI-001453
    - CCI-002418
    - SRG-OS-000250-GPOS-00093
    - SRG-OS-000423-GPOS-00187
    - SV-258238r926701_rule
    - V-258238
    - NIST800-53R4_AC-17
    - NIST800-53R4_SC-8
  block:
    - name: HIGH | RHEL-09-672030 | AUDIT | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Capture crypto state
      ansible.builtin.shell: update-crypto-policies --show
      changed_when: false
      register: crypto_policies_state

    - name: HIGH | RHEL-09-672030 | PATCH | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Enable FIPS
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - rhel9stig_disruption_high
      ansible.builtin.shell: fips-mode-setup --enable
      notify: Change_requires_reboot

    - name: HIGH | RHEL-09-672030 | WARN | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Give Warning
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.debug:
        msg: WARNING!! - Crypto-Policies is not set to FIPS

    - name: HIGH | RHEL-09-672030 | WARN | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Warning Count
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.import_tasks: warning_facts.yml
      vars:
        warn_control_id: RHEL-09-672030
