---
- name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled
  when:
    - rhel_09_211050
  notify: Systemd_reload
  tags:
    - RHEL-09-211050
    - CAT1
    - CCI-000366
    - CCI-002235
    - SRG-OS-000324-GPOS-00125
    - SRG-OS-000480-GPOS-00227
    - SV-257785r925342_rule
    - V-257785
    - NIST800-53R4_CM-6
    - NIST800-53R4_AC-6
  block:
    - name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled | systemctl disable
      ansible.builtin.systemd:
        enabled: false
        masked: true
        name: ctrl-alt-del.target
        state: stopped
      notify: Systemd_daemon_reload

    - name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled | Create symlink to /dev/null
      ansible.builtin.file:
        dest: /etc/systemd/system/ctrl-alt-del.target
        src: /dev/null
        state: link
      notify: Systemd_daemon_reload
